apiVersion: v1
kind: Service
metadata:
  name: swe645-webapp-service
  labels:
    app: swe645-webapp
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: swe645-webapp